import type { Project } from "./definition";

export const projectData: Project[] = [
  {
    name: "Dashboad Acme",
    linkWebsite: "https://nextjs-dashboard-nu-pearl-48.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/nextJs-course/tree/main/nextjs-dashboard",
    img: "/project/dashboard.png",
    mostUsedTools: ["React", "Typescript", "TailwindCSS", "Next.Js"],
    allTools: ["Vercel"],
  },
  {
    name: "VazzChat App",
    linkWebsite: "https://vazzchat.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/typescript-tailwind-exercise/tree/main/chat-room",
    img: "/project/vazzchat.jpg",
    mostUsedTools: ["React", "Redux", "Typescript", "TailwindCSS", "Firebase(RD)"],
    allTools: ["Vite", "SCSS", "Vercel"],
  },
  {
    name: "Netflix Clone",
    linkWebsite: "https://netflix-clone-ivaz.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/netflix-clone",
    img: "/project/netflixSiteSS.png.png",
    mostUsedTools: ["React", "SCSS", "Redux", "Firebase(RD)", "TMDB"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Weather App",
    linkWebsite: "https://weather-app-blush-seven-98.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/redux-project/tree/main/weatherApp",
    img: "/project/weather.png",
    mostUsedTools: ["React", "SCSS", "Redux", "Openweather"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Amazon Clone",
    linkWebsite: "https://ivaz7.github.io/Amazon-Clone-Project/amazon.html",
    linkPreview: "https://github.com/Ivaz7/Amazon-Clone-Project",
    img: "/project/amazon.png",
    mostUsedTools: ["Javascript", "HTML"],
    allTools: ["CSS"],
  },
  {
    name: "Assembly: Endgame",
    linkWebsite: "https://assembly-game-nine.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/react-course/tree/master/assembly-game",
    img: "/project/asembly.png",
    mostUsedTools: ["React", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Tenzies Game",
    linkWebsite: "https://tenzies-game-five-rho.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/react-course/tree/master/tenzies-game",
    img: "/project/tenzies.jpg",
    mostUsedTools: ["React", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Meme Editor",
    linkWebsite: "https://meme-editor-gray.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/react-course/tree/master/meme-editor",
    img: "/project/meme.png",
    mostUsedTools: ["React", "SCSS", "Img Flip"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Pokemon Search App",
    linkWebsite: "https://ivaz7.github.io/Javascript-freeCodeCamp/Pokemon-search-app/pokemonSearch.html",
    linkPreview: "https://github.com/Ivaz7/Javascript-freeCodeCamp/tree/main/Pokemon-search-app",
    img: "/project/pokemon.jpg",
    mostUsedTools: ["Javascript", "CSS", "Pokemon API"],
    allTools: ["HTML"],
  },
  {
    name: "Cheff Hugging Face A.I.",
    linkWebsite: "https://cooking-recipe-ai-project.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/react-course/tree/master/cooking-recipe-claude-project",
    img: "/project/cheff.jpg",
    mostUsedTools: ["React", "Hugging Face", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Workout Clock",
    linkWebsite: "https://workout-app-gray.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/Front-end-freeCodeCamp/tree/main/WorkoutClock",
    img: "/project/workout.png",
    mostUsedTools: ["React", "Redux", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Drum Kit App",
    linkWebsite: "https://drumkit-app-one.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/Front-end-freeCodeCamp/tree/main/drumKitApp",
    img: "/project/drum.png",
    mostUsedTools: ["React", "Redux", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Calculator App",
    linkWebsite: "https://calculator-app-sepia-tau.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/Front-end-freeCodeCamp/tree/main/calculatorApp",
    img: "/project/calculator.png",
    mostUsedTools: ["React", "Redux", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Random Quote App",
    linkWebsite: "https://random-quote-app-tau.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/Front-end-freeCodeCamp/tree/main/RandomQuoteApp",
    img: "/project/quote.png",
    mostUsedTools: ["React", "Redux", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Markdown Editor",
    linkWebsite: "https://markdown-editor-iota-liard.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/Front-end-freeCodeCamp/tree/main/markdownEditorApp",
    img: "/project/markdown.jpg",
    mostUsedTools: ["React", "Redux", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Palindrome Checker App",
    linkWebsite: "https://ivaz7.github.io/Javascript-freeCodeCamp/Palindrome-checker-page/palindrome.html",
    linkPreview: "https://github.com/Ivaz7/Javascript-freeCodeCamp/tree/main/Palindrome-checker-page",
    img: "/project/palindrome.jpg",
    mostUsedTools: ["Javascript", "CSS"],
    allTools: ["HTML"],
  },
  {
    name: "Roman Numeral Converter App",
    linkWebsite: "https://ivaz7.github.io/Javascript-freeCodeCamp/Roman-Numeral-Converter/RomanNumConvert.html",
    linkPreview: "https://github.com/Ivaz7/Javascript-freeCodeCamp/tree/main/Roman-Numeral-Converter",
    img: "/project/numeral.jpg",
    mostUsedTools: ["Javascript", "CSS"],
    allTools: ["HTML"],
  },
  {
    name: "Cash Register App",
    linkWebsite: "https://ivaz7.github.io/Javascript-freeCodeCamp/Cash-register-project/cashRegister.html",
    linkPreview: "https://github.com/Ivaz7/Javascript-freeCodeCamp/tree/main/Cash-register-project",
    img: "/project/cash.jpg",
    mostUsedTools: ["Javascript", "CSS"],
    allTools: ["HTML"],
  },
  {
    name: "Telephone Number Validator (US) App",
    linkWebsite: "https://ivaz7.github.io/Javascript-freeCodeCamp/Telephone-number-validator/phoneNumValidator.html",
    linkPreview: "https://github.com/Ivaz7/Javascript-freeCodeCamp/tree/main/Telephone-number-validator",
    img: "/project/phone.jpg",
    mostUsedTools: ["Javascript", "CSS"],
    allTools: ["HTML"],
  },
  {
    name: "Youtube Clone (Static)",
    linkWebsite: "https://ivaz7.github.io/HTML-CSS-courses/Youtube%20Fake%20Page%20Projects/youtube.html",
    linkPreview: "https://github.com/Ivaz7/HTML-CSS-courses/tree/main/Youtube%20Fake%20Page%20Projects",
    img: "/project/youtube.jpg",
    mostUsedTools: ["HTML", "CSS"],
  },
  {
    name: "Journal Travel",
    linkWebsite: "https://journal-travel-project.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/react-course/tree/master/Journal-travel-project",
    img: "/project/travel.png",
    mostUsedTools: ["React", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Fun Fact About React",
    linkWebsite: "https://fun-fact-react-project.vercel.app/",
    linkPreview: "https://github.com/Ivaz7/react-course/tree/master/Fun-fact-react-project",
    img: "/project/funfact.png",
    mostUsedTools: ["React", "SCSS"],
    allTools: ["Vite", "Vercel", "Bootstrap"],
  },
  {
    name: "Survey Form",
    linkWebsite: "https://ivaz7.github.io/HTML-CSS-freeCodeCamp/Survey%20Form/surveyformnew.html",
    linkPreview: "https://github.com/Ivaz7/HTML-CSS-freeCodeCamp/tree/master/Survey%20Form",
    img: "/project/survey.jpg",
    mostUsedTools: ["HTML", "CSS"],
  },
  {
    name: "Laning Page",
    linkWebsite: "https://ivaz7.github.io/HTML-CSS-freeCodeCamp/Laning%20Page/laning-page.html",
    linkPreview: "https://github.com/Ivaz7/HTML-CSS-freeCodeCamp/tree/master/Laning%20Page",
    img: "/project/piano.jpg",
    mostUsedTools: ["HTML", "CSS"],
  },
  {
    name: "Technical Documentation",
    linkWebsite: "https://ivaz7.github.io/HTML-CSS-freeCodeCamp/Technical%20Documentation%20Page/TechDoc.html",
    linkPreview: "https://github.com/Ivaz7/HTML-CSS-freeCodeCamp/tree/master/Technical%20Documentation%20Page",
    img: "/project/techdoc.jpg",
    mostUsedTools: ["HTML", "CSS"],
  },
  {
    name: "Tribute Page",
    linkWebsite: "https://ivaz7.github.io/HTML-CSS-freeCodeCamp/Tribute%20Page/tributepagenew.html",
    linkPreview: "https://github.com/Ivaz7/HTML-CSS-freeCodeCamp/tree/master/Tribute%20Page",
    img: "/project/tribute.jpg",
    mostUsedTools: ["HTML", "CSS"],
  },
];
