import { Quote } from "./definition";

export const quoteData: Quote[] = [
  { quote: "Talk is cheap. Show code.", from: "Linus Torvalds" },
  { quote: "Code for people, not just machines.", from: "Harold Abelson" },
  { quote: "Good code is easy to understand.", from: "Martin Fowler" },
  { quote: "Solve the problem, then code.", from: "John Johnson" },
  { quote: "If code needs explaining, it's bad.", from: "Cory House" },
  { quote: "Optimism is a bug. Feedback fixes it.", from: "Kent Beck" },
  { quote: "Programming is about solving, not knowing.", from: "Chris Pine" },
  { quote: "Simplicity drives efficiency.", from: "Austin Freeman" },
  { quote: "Usability comes before reusability.", from: "Ralph Johnson" },
  { quote: "Make it work, then perfect it.", from: "Kent Beck" },
  { quote: "Debugging is fixing what we broke.", from: "Edsger W. Dijkstra" },
  { quote: "Start sooner, finish faster.", from: "Jim Highsmith" },
  { quote: "Good software makes complexity simple.", from: "Grady Booch" },
  { quote: "A language should change how you think.", from: "Alan Perlis" },
  { quote: "Software grows like entropy—always.", from: "Norman Augustine" },
  { quote: "A program must serve its user.", from: "C.A.R. Hoare" },
  { quote: "Write code as if someone else will maintain it.", from: "John Woods" },
  { quote: "Don’t let complexity confuse you.", from: "Edsger W. Dijkstra" },
  { quote: "Better programs, smarter users. Universe wins.", from: "Rick Cook" },
  { quote: "You never know what a programmer does—until it’s too late.", from: "Seymour Cray" },
  { quote: "Lines of code don’t measure progress.", from: "Bill Gates" },
  { quote: "The best error message is no error message.", from: "Thomas Fuchs" },
  { quote: "Without design, code is just bugs.", from: "Louis Srygley" },
  { quote: "Experts remove bad code, not patch it.", from: "Richard Pattis" },
  { quote: "To iterate is human, to recurse divine.", from: "L. Peter Deutsch" },
  { quote: "Great devs solve problems beyond their skills.", from: "Patrick McKenzie" },
  { quote: "Computers follow instructions, not thoughts.", from: "Donald Knuth" },
  { quote: "Code is honest, comments aren’t always.", from: "Ron Jeffries" },
  { quote: "A good coder checks both ways on one-way streets.", from: "Doug Linder" }
];